### ISSUE TITLE
initialized website template file has errors

### ISSUE THREAD

**Issue by hongsw** [Dalgona/Serum#23] opened 2018-04-05 07:00 UTC
I expected that generated "hello serum world" site after this commands

```
serum init ./newsite
cd ./newsite
serum build
```
but, I got error 
```
Several errors occurred from build_pass2:
  Several errors occurred from page_builder:
    ❌  ./templates/page.html.eex:1: undefined function contents/0
  Several errors occurred from to_fragments:
    ❌  ./templates/list.html.eex:1: undefined function header/0
```

Where should I look at the source?

**Comment by Dalgona** [comment] 2018-04-05 09:51
A few weeks ago I made a lot of breaking changes (which are not thoroughly documented yet), and some source files don't seem to be updated accordingly. In this case, templates for the new project (`priv/build_resources/includes/*.html.eex` and `priv/build_resources/templates/*.html.eex`) may be stale. Let me fix this real quick :sweat_drops::sweat_drops:

**Comment by Dalgona** [comment] 2018-04-05 13:09
It takes very little time to fix these templates, but the corresponding user manual should be completely rewritten. 😢

**Comment by hongsw** [comment] 2018-04-09 06:25
I will try to rewrite it. Thanks :)

**Comment by Dalgona** [comment] 2018-06-14 00:08
I just pushed a commit which resolves the issue.

This issue was caused by some breaking changes in template variables. However, these changes are not fully documented yet, so you might have some difficulties extending your templates.

Please consult the source code of serum-site project (https://github.com/Dalgona/serum-site/tree/master/templates) until the docs are completed.

Alternatively, you can check which variables are available in each page by injecting codes like

```
<pre><code><%= inspect assigns, pretty: true, width: 100 %></code></pre>
```

in templates/base.html.eex file.

I will close this issue after the docs are completed. Sorry for inconveniences!

**Closed** 2018-12-10 09:48 UTC
